### PR TITLE
BI-397-Buildbot-add-the-ability-to-list-builds

### PR DESCRIPTION
**Pull request by sonnguyen-logigear**
API rest call: https://build.ankicore.com/app/rest/builds?locator=running:true - bot command = "@buildbot running"
API rest call: https://build.ankicore.com/app/rest/buildQueue - bot command = "@buildbot queue"

### CODE REVIEW

**Comment by scopp** [comment]
@sonnguyen-logigear please remove `Use a build `id` from the list to trigger a build. *@buildbot build id*` from the response

**Comment by sonnguyen-logigear** [comment]
- Sometime build have no branch or branch is a text not is a pull request number, then I think we should show "branch name" (not pull request number)
- I cant create hyperlink for build number(this can be done if we send text for webhook bot) then I had use full link at the end.
- I had build team city server in local to test **queue** command
-Result as below :

queue
running

Please help me review @scopp

**Comment by scopp** [comment]
Can we change the format to:
`BuildName :: buildNumber=55 :: %complete=50 :: branchName=none`

The BuildName should be a hyperlink to the build, for example in the en.yml:
`<%{url}|%{BuildName}>`

**Comment by sonnguyen-logigear** [comment]
I had try to use format to make hyperlink before, but can not. This [link ](https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages)said that :  Hyperlinking words and terms in a Slack message isn't supported — to include a URL, paste it into the message input box.

I had made block for each build to see clearly as :+1: 

running
queue

Please help me review.

**Pull request merged**
