### PR TITLE
Revert "BI-1340-TC-lita-bot-security-vulnerability"

### PR DESCRIPTION
**Pull request by scopp**
Reverts scopp/lita-slack-teamcity#14

### CODE REVIEW

**Comment by scopp** [comment]
@thanhlelgg please also update the Gemfile.lock as well as part of this update.

**Comment by sonnguyen-logigear** [comment]
@scopp please help me review

**Comment by scopp** [comment]
@sonnguyen-logigear don't you need to update `workspace/lita-teamcity.gemspec` as well?

**Comment by sonnguyen-logigear** [comment]
@scopp That is already in master.

**Pull request merged**
